"""imp

Revision ID: 3d2e8c31f74c
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '3d2e8c31f74c'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
