"""imp

Revision ID: abded17e51b8
Revises: 3d2e8c31f74c
"""
from alembic import op
import sqlalchemy as sa


revision = 'abded17e51b8'
down_revision = '3d2e8c31f74c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
